version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - db
    networks:
      - flask-network
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "app.py"]
    volumes:
      - .:/app 

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5433:5432"
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge
